### ISSUE TITLE
SqlHierarchy doesn't produce child ids properly

### ISSUE THREAD

**Issue by jmounce** [dotMorten/Microsoft.SqlServer.Types#10]
I think this [line](https://github.com/dotMorten/Microsoft.SqlServer.Types/blob/master/src/Microsoft.SqlServer.Types/SqlHierarchyId.cs#L149) needs to change to:
`public SqlHierarchyId GetDescendant(SqlHierarchyId child1, SqlHierarchyId child2) => new SqlHierarchyId(_imp.GetDescendant(child1.IsNull ? default(HierarchyId?) : child1._imp, child2.IsNull ? default(HierarchyId?) : child2._imp));`
Otherwise, you can't create the first child. Unless I'm missing something...

**Comment by dotMorten** [comment]
Thanks. So you have an example I can use for a unit test to confirm behavior?

**Comment by dotMorten** [comment]
Thanks!  Fixed with https://github.com/dotMorten/Microsoft.SqlServer.Types/commit/ad8744f9f1360e785bf70356c81ba95747c4e4a0
