### ISSUE TITLE
GetAncestor() fails when querying top-level node

### ISSUE THREAD

**Issue by jmounce** [dotMorten/Microsoft.SqlServer.Types#11]
I believe there is a problem with the implementation of HierarchyId/SqlHierarchyId.
On [this line](https://github.com/dotMorten/Microsoft.SqlServer.Types/blob/master/src/Microsoft.SqlServer.Types/SqlHierarchy/HierarhyId.cs#L100), the condition result is too severe, resulting in thrown exceptions during EF queries.
The exception, also, is not very intuitive and is hard to see. It just says:
"ArgumentException: n"

For example, a query that finds the children of a parent:
`			
IQueryable<employee> children =
	from e in _ctx.employees
	where (e.HierarchyId.GetAncestor(1) == parent.HierarchyId).IsTrue
	select e;
`
it will except/throw and the query will not run.

I believe the correct solution is to return null (changing the signature of the function to return a Nullable<HierarchyId>.
The only consequence I see, is that [this line](https://github.com/dotMorten/Microsoft.SqlServer.Types/blob/master/src/Microsoft.SqlServer.Types/SqlHierarchyId.cs#L129) needs to change to:
`
	        HierarchyId? retVal = _imp.GetAncestor(n);
	        return retVal.HasValue ? new SqlHierarchyId(retVal.Value) : Null;
`
I *believe* this is correct because I don't know where this source code came from and whether there is a fundamental constraint in the library I am not understanding.

I don't have a unit test that is easy to give to you as you have no EF tests to begin with.
You may want to incorporate some EF tests and run a similar query as above.

**Comment by dotMorten** [comment]
> (changing the signature of the function to return a Nullable

I can't change the signature of any methods, as that would diverge from the original .NET Framework assembly.

What behavior are you seeing when using Microsoft's .NET Framework version of this assembly?

> I don't have a unit test that is easy to give to you as you have no EF tests to begin with.

EF shouldn't be needed. The query generated that throws the exception should be enough.

**Comment by dotMorten** [comment]
I think this might be what you're trying to do?

```cs
        [TestMethod]
        public void GetParentOfRootNode()
        {
            var root = Microsoft.SqlServer.Types.SqlHierarchyId.GetRoot();
            var parent = root.GetAncestor(1);
            Assert.IsTrue(parent.IsNull);
        }
```

That does indeed fail on this implementation and parses on the Microsoft one

**Comment by dotMorten** [comment]
I made a fix for this particular issue. If this wasn't what you were hitting, please reopen
