### ISSUE TITLE
EF Queries are inefficient

### ISSUE THREAD

**Issue by jmounce** [dotMorten/Microsoft.SqlServer.Types#12]
A query such as:
`
	from o in _ctx.Organization
	where (myorg.HierarchyId.GetAncestor(1) == o.HierarchyId).IsTrue
	select o
`
results in this SQL:
`
SELECT [o].[OrganizationId], [o].[HierarchyId], [o].[Name]
FROM [Organization] AS [o]
ORDER BY [o].[HierarchyId]
`
instead of:
`
SELECT [o].[OrganizationId], [o].[HierarchyId], [o].[Name]
FROM Organization
WHERE @HierarchyId.GetAncestor(1) = [HierarchyId]
`
In fact, any queries involving the HierarchyId functions result in a table dump.
This is definitely inefficient for a large table.

**Comment by dotMorten** [comment]
You should log this issue in EF Core as this has nothing to do with this assembly, since the library doesn't generate any SQL statements. I'm assuming EF Core is doing that.
