### ISSUE TITLE
Error with GetDescendent

### ISSUE THREAD

**Issue by geoFlux** [dotMorten/Microsoft.SqlServer.Types#21]
This causes an IndexOutOfRange Exception:
```
var newSibling = SqlHierarchyId.Parse("/1/").GetDescendant(
		SqlHierarchyId.Parse("/1/1/"),
		SqlHierarchyId.Parse("/1/1.1/")
	)
```

**Comment by dotMorten** [comment]
Submitted a fix. TBH I'm not 100% it is the right fix, but in this specific scenario, it now returns the same value as SQL Server would

**Comment by dotMorten** [comment]
Also @olmobrutall (who provided the SqlHierarchyId implementation) might be able to better judge if my fix was correct or not.
