### ISSUE TITLE
Inconsistent usage of FigureAttributes

### ISSUE THREAD

**Issue by MuhKuh7** [dotMorten/Microsoft.SqlServer.Types#25]
The current `FigureAttributes` is inconsistently used and mixes V1 and V2 values.
For example `WktReader.ReadPolygon` uses the V1 value `FigureAttributes.ExteriorRing` and `WktReader.ReadPoint` uses the V2 value `FigureAttributes.Point`.

This leads to incorrect byte representation in the Serialize function.

**Comment by dotMorten** [comment]
Could you share an example of a unit test that that would fail, but works with the official implementation? This is a hard to fix issue without any examples.

**Comment by MuhKuh7** [comment]
I don't remember. This was too long ago.

**Comment by dotMorten** [comment]
Thanks. And sorry I’ve been a bit off this project for a while
