### ISSUE TITLE
Usage with SqlBulkCopy

### ISSUE THREAD

**Issue by skolima** [dotMorten/Microsoft.SqlServer.Types#27]
Thanks for your great work! I've managed to write into DB with SqlBulkCopy, using the following:

```
table.Columns.Add("Geocode", typeof(byte[]));
```

and then in `Rows.Add`:

```
SqlGeography.Point(location.Latitude.Value, location.Longitude.Value, 4326).Serialize().Value
```

is this how it's supposed to work? Seems a bit roundabout, but it works. If yes, then perhaps this would be useful to include in the Readme.md?

**Comment by dotMorten** [comment]
I'm not sure why you make it a byte array and serialize it? SqlGeography is an actual type in sqlserver.
So not that's not how it's supposed to work, but sure it can work 😃

**Comment by skolima** [comment]
Oh! You're absolutely right. I've been through so many errors trying to bulk insert the geography from a dotnet core 2.2 app that I didn't realise how simple this is. Thanks!

**Comment by dotMorten** [comment]
Hah. Yeah this is sort of the entire point of this library. To make it simple where this type isn't really supported
