### ISSUE TITLE
Some missing APIs on SqlGeography

### ISSUE THREAD

**Issue by MaceWindu** [dotMorten/Microsoft.SqlServer.Types#28]
I've tried to enable some .net framework tests we have to run under .net core too and found out that there are some missing APIs:
- SqlGeography.GeomFromGml()
- SqlGeography.AsGml()
- SqlGeography.STEquals()

Not sure how it is important, as we don't really need those methods - it's just a part of our test suite

**Comment by dotMorten** [comment]
I have no plans to add geometry operations, as those are near-impossible to get exactly like what the server does without knowing the source code behind it. You should use SQL server to perform these operations as part of your SQL query

**Comment by MaceWindu** [comment]
Ok, that's fine for us. We just don't call them in tests against your lib

**Comment by dotMorten** [comment]
Closing as out of scope
