### ISSUE TITLE
SqlHierarchyId support?

### ISSUE THREAD

**Issue by KarloX2** [dotMorten/Microsoft.SqlServer.Types#3]
Hi!
Do you plan to support SqlHierarchyId, too?
Thanks,
Karlo

Doc reference: https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.types.sqlhierarchyid.aspx
```
[SqlUserDefinedTypeAttribute(Format.UserDefined, IsByteOrdered = true, 
	MaxByteSize = 892, Name = "SqlHierarchyId")]
public struct SqlHierarchyId : IBinarySerialize, INullable, IComparable
```

> This type provides the following benefits for storing hierarchical information:
> - Very compact data storage.
> - Depth-first comparison. Indexes on this type are in depth-first order, and nodes close to each other in a depth-first traversal are stored near each other.
> - Support for arbitrary insertions and deletions.
> - A limitation of this type is that a single instance of the hierarchy data type can be no larger than 892 bytes. Hierarchies that possess too many levels to fit within this limitation must use a different data type.

Example
```DECLARE @employee hierarchyid
SELECT @employee = OrgNode FROM HumanResources.EmployeeDemo
  WHERE LoginID = 'adventure-works\dylan0'

SELECT * FROM HumanResources.EmployeeDemo
WHERE @employee.IsDescendantOf(OrgNode) = 1
```

Example for creating hierarchy table: https://technet.microsoft.com/en-us/library/bb630263(v=sql.110).aspx

**Comment by dotMorten** [comment]
That shouldn't be a problem, as it looks pretty simple. However I have no idea what that's for, as I've never needed that myself. Any chance you could write some unit tests for inserting and querying them, and I'll make them pass? (Look at the two unit test classes that are already there for inspiration).
You could just write the tests against the "real" types assembly. I can then pull them in and make things compile and pass.

**Comment by KarloX2** [comment]
Having support for SqlHierarchyId would be extremly useful when working with such data with clients where the underlying native dll can't run. Yes, I'll try to provide something, but that can't happen before something like May, 10th. Ok for you?

Thanks!

**Comment by dotMorten** [comment]
@KarloX2 Sounds good. Before you do, double check this issue to ensure I haven't already somehow done it by then :-)

**Comment by dotMorten** [comment]
Completed. Thanks @olmobrutall
