### ISSUE TITLE
Strong name?

### ISSUE THREAD

**Issue by asherber** [dotMorten/Microsoft.SqlServer.Types#30]
I'm getting an error when trying to use this library:

```
FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

The listing for the NuGet package indicates that the assembly is strong name signed, but when I pull out the assembly and look at it in ILSpy, it doesn't appear to be.

**Comment by dotMorten** [comment]
The listing is wrong. It's not currently strong-name signed.
