### ISSUE TITLE
SqlHierarchyId.Null seems to have changed value

### ISSUE THREAD

**Issue by brumlemann** [dotMorten/Microsoft.SqlServer.Types#31]
Microsoft.SqlServer.Types v12.0.0.0:

SqlHierarchyId.Null = {NULL}

dotMorten/Microsoft.SqlServer.Types:

SqlHierarchyId.Null = {/}

Which in turn means that 

SqlHierarchyId.GetRoot().Equals(SqlHierarchyId.Null) == true

which doesn't seem right. It also leads to changes in GetAncestor(n) behaviour for n > GetLevel() because ti doesn't distinguish between this case and the case n=GetLevel() (i.e. root).

**Comment by dotMorten** [comment]
Thanks. Just so I'm sure what you're getting at, if you had to express it as a unit test like these: https://github.com/dotMorten/Microsoft.SqlServer.Types/blob/master/src/Microsoft.SqlServer.Types.Tests/HierarchyId/SqlHierarchyIdTests.cs
what would that look like?
We could add it as a test case (the test runner is set up to compare behavior between Microsoft's and this implementation, so it should parse in one case, and fail in the other)

**Comment by brumlemann** [comment]
What about these?

            Assert.AreNotEqual(SqlHierarchyId.GetRoot(), SqlHierarchyId.Null);
            Assert.AreEqual(SqlHierarchyId.GetRoot().GetAncestor(1), SqlHierarchyId.Null);

The first assert fails, and shouldn't IMHO. The second assert passes and it should.

**Comment by dotMorten** [comment]
Fixed!

**Comment by brumlemann** [comment]
Hi Morten. Was this ever merged/released/deployed?
