### ISSUE TITLE
DataReader.GetFieldType returned null

### ISSUE THREAD

**Issue by unruledboy** [dotMorten/Microsoft.SqlServer.Types#32]
hi,

Regardless whether I use Microsoft.SQLServer.Types or your implementation, it always give me the "DataReader.GetFieldType returned null" message whenever I query a table with a column as geography type, even there is NO data in the result.

Could you please shed some light on this?

Thanks,
Wilson

**Comment by dotMorten** [comment]
Could you provide a repro? Preferably as a unit test added to the project showing it passes for .net framework tests (which uses the official library) but fails with this implementation?

Without more info like that I can't really provide any guidance or help with the bug as the above has very limited information and I'm terrible at guessing.
