### ISSUE TITLE
HierarchyId inconsistency

### ISSUE THREAD

**Issue by Liklainy** [dotMorten/Microsoft.SqlServer.Types#34]
Hello! Thanks for your hard work! 😄
In real data set I have encountered an hierarchyid like this:
```
/9138844059576.194933736431247.745612732/136587127227772.29968291099783.2405269301/194815533346310.190518957122630.1754824175/131180557026026.166347272232468.2634227923/112680214461405.155342927909666.4090640326/38488193629220.193847278467647.3890935971/
```
And I was not able to parse it with `SqlHierarchyId` implementation in this library

Encountered two blockers:
1. This string cannot be parsed by `SqlHierarchyId`, because underlying node type is `int` (PR #33)
2. Cannot parse binary representation because there are no patterns for this case

The real problem is the second blocker.
It seams that current patterns don't implement all cases.

**Comment by dkearney1** [comment]
This issue is holding me up too. I believe PR #33 would fix my issue.

**Comment by Liklainy** [comment]
Hello, @dkearney1,
For patterns you can look at #6 and [this link](http://www.adammil.net/blog/v100_how_the_SQL_Server_hierarchyid_data_type_works_kind_of_.html) (you can find the same link in PR)

**Comment by dkearney1** [comment]
@Liklainy I have admit that my bit-twiddling skills are not up to the task of creating additional patterns, even after having read the documentation you linked. Should I be engaging the article's author about this?

**Comment by dotMorten** [comment]
Seems to be working just fine with latest source code, likely with PR 33 that changed it to use longs for parsing instead. Added a unit test also to ensure this won't regress
