### ISSUE TITLE
HierarchyId >= operator typo

### ISSUE THREAD

**Issue by cutig3r** [dotMorten/Microsoft.SqlServer.Types#36]
The underlying operator for >= is using <=
https://github.com/dotMorten/Microsoft.SqlServer.Types/blob/6411231031c1f2c2cf74f4f086ed6aa8f6371450/src/Microsoft.SqlServer.Types/SqlHierarchy/HierarhyId.cs#L368 
it should be
`public static bool operator >=(HierarchyId hid1, HierarchyId hid2) => Compare(hid1, hid2) >= 0;`

**Comment by dotMorten** [comment]
@cutig3r I totally see what you're seeing and it makes sense that it's wrong. However I've had a hard time confirming this issue is actually a bug. The following test seems to pass both against the official libraries and this one:
```cs
        [TestMethod]
        [WorkItem(36)]
        public void OperatorComparison()
        {
            var h1 = SqlHierarchyId.Parse("/9/2/");
            var h2 = SqlHierarchyId.Parse("/9/1/");
            var h3 = SqlHierarchyId.Parse("/9/1/");
            Assert.IsTrue((bool)(h1 >= h2));
            Assert.IsTrue((bool)(h2 <= h1));
            Assert.IsFalse((bool)(h1 <= h2));
            Assert.IsFalse((bool)(h2 >= h1));
            Assert.IsFalse((bool)(h1 == h2));
            Assert.IsTrue((bool)(h3 >= h2));
        }
```
