### ISSUE TITLE
Unable to load DLL 'SqlServerSpatial140.dll' or one of its dependencies - on linux server - docker container

### ISSUE THREAD

**Issue by salantastefan** [dotMorten/Microsoft.SqlServer.Types#37]
I am using the 14.0.1016.290 version of the package on .NET core and I have fixed the problem locally (on a windows machine) by copying SqlServerSpatial140.dll from the temporary package folder to the root of my project, and set the property 'Copy to Output Directory' to 'Copy always'.

However, now I am trying to deploy the build to a linux alpine server running a docker container and I am getting the error 'Unable to load DLL 'SqlServerSpatial140.dll' or one of its dependencies' . The dll is on the same location on the server as it is on the local machine build folder.

Is the package compatible with linux? Do I have to move it in a different/new folder?

**Comment by dotMorten** [comment]
This package doesn't take a dependency on that dll. Sounds like you referenced the original Microsoft package instead.

**Comment by salantastefan** [comment]
Upps, that is correct, thanks
