### ISSUE TITLE
Potential updated release?

### ISSUE THREAD

**Issue by petertirrell** [dotMorten/Microsoft.SqlServer.Types#40]
I've been porting my application to .NET Core 3.1 and am using this package in lieu of the official SqlServer.Types package that is not .NET Standard compliant.  I was running into a problem where I would get a "FormatException" error saying "Invalid Well-known Text" when trying to create a SqlGeometry like this:

```
var wkt = "POINT(29.41824 45.99194)";
var value = SqlGeometry.STGeomFromText(new SqlChars(new SqlString(wkt)), 4326);
```

After various troubleshooting and digging around, I ended up pulling down the source code, including the project directly in my solution instead of using the nuget package, and my code worked.  Looking through the commit history it looks like there were some changes (and other improvements?) since the 1.1 release in 2018.  

Are there any plans to provide an updated release, possibly even compiled to .NET Standard 2.1?  Or, given my example above, what should the correct syntax be to create a SqlGeometry from a WKT string?

Thanks,

**Comment by dotMorten** [comment]
I'll look into it. Curious why you need a netstd2.1 release though? 2.0 can be used with 2.1

**Comment by petertirrell** [comment]
Thanks!  Re: std2.1, no real reason, I was just poking around trying to compile with latest when I was doing my troubleshooting.  You are correct - 2.0 is working fine in my project!

**Comment by dotMorten** [comment]
Trying to wrap some things up now. Hopefully out this week

**Comment by dotMorten** [comment]
v1.2 now available on nuget.org
