### ISSUE TITLE
default(SqlHierarchyId) does not set IsNull property to true

### ISSUE THREAD

**Issue by andreaskoepf** [dotMorten/Microsoft.SqlServer.Types#44]
I noticed that the default value of the dotMorten `SqlHierarchyId` struct differs from Microsoft's original `SqlHierarchyId` implementation in the point that the `default(SqlHierarchyId)` value of the drop-in is not NULL (e.g. `IsNull == false`) while the original implementation produces a NULL value as default-value.

@olmobrutall Maybe you can comment on this? In the original impl `OrdPath` (what is `HierarchyId` in this project) is a class and therefor can be `null`.

**Comment by andreaskoepf** [comment]
I have temporarily fixed this locally with a custom build derived from @olmobrutall 's https://github.com/olmobrutall/Microsoft.SqlServer.Types (PR #38). By using:
```
private bool hasValue;
public bool IsNull => !hasValue;
```

I am setting `hasValue` to `!isNull` in the ctor and to `true` in `SqlHierarchyId.Read()`...

**Comment by brumlemann** [comment]
Is this related to #31 ?

**Comment by andreaskoepf** [comment]
@brumlemann No, it is not directly related to the `CompareTo()` fix.

**Comment by dotMorten** [comment]
Unit test for verification:
```cs
        [TestMethod]
        [WorkItem(44)]
        public void DefaultIsNull()
        {
            var h = default(SqlHierarchyId);
            Assert.IsTrue(h.IsNull);
        }
```

**Comment by andreaskoepf** [comment]
@dotMorten 👍 thx a lot!
