### ISSUE TITLE
GetDescendant for a simple range fails with a HierarchyIdException

### ISSUE THREAD

**Issue by AndyBates6668** [dotMorten/Microsoft.SqlServer.Types#46]
The following unit test fails with the current code:

        [TestMethod]
        public void InsertTopLevelNodeBetweenNodes()
        {
            var id = SqlHierarchyId.GetRoot();
            var idChild = id.GetDescendant(SqlHierarchyId.Parse("/0/"), SqlHierarchyId.Parse("/1/"));
            Assert.AreEqual("/0.1/", idChild.ToString());
        }

**Comment by AndyBates6668** [comment]
I'll see what I can do to resolve the issue.

**Comment by ppasieka** [comment]
@AndyBates6668 I have a fix for this issue. Tomorrow I will try to create a PR
