### ISSUE TITLE
Deserialize to SqlGeometry or SqlGeography 

### ISSUE THREAD

**Issue by AlenToma** [dotMorten/Microsoft.SqlServer.Types#5]
Hi im new to SqlGeography and would like to implement this future to my library 
[EntityWorker.Core](https://www.nuget.org/packages/EntityWorker.Core/)
im having problem saving those value to sqllite and postgress and mysql so i decided to use nvarchar(max)
as column datatype is this good ? 
ok i would like to know if there is a way to extract those value from the db as nvarchar and Deserialize to SqlGeometry or SqlGeography 

how should i think could you please help

**Comment by dotMorten** [comment]
I have no idea, but you can serialize to/from binary `byte[]` with this lib, so I'm guessing you should be storing a binary data?
