### ISSUE TITLE
Some Geography cannot be deserialized.

### ISSUE THREAD

**Issue by yorek** [dotMorten/Microsoft.SqlServer.Types#50]
This Geography:

WKBF:
0xE610000002241B0000001C812C5F17D24740C5F8D8708E885EC05C5D8C9918D24740C57CD7938E885EC08462D48918D24740C5406ACA88885EC0BCB3D0DA06D24740C6EAC19B88885EC05C8A60BB06D24740C418796C87885EC04011C2EC09D24740C49C778F87885EC0E82B0ADD09D24740C5348AC885885EC058CB0AD40BD24740C5348AC885885EC0B0C3E2A40BD24740C6B037897D885EC034BDDEC803D24740C47AE44E7D885EC0347926B903D24740C5DAD4CF7E885EC080D9732900D24740C4067FDB7E885EC078ECE34800D24740C4DEB78B81885EC0D4395FF1F3D14740C5580D8081885EC0F8AEF448F2D14740C668A62F83885EC038009C7CF1D14740C4E4D11A87885EC0BCD115DD02D24740C4E4D11A87885EC0DCC1A5BD02D24740C626663389885EC0381B7C9700D24740C5AA645689885EC064323B1EFFD14740C5D255B48A885EC0E4CC5ADFFED14740C4CE653891885EC0AC8514E600D24740C5F8027F92885EC0E8DD4FDF05D24740C4B0A8F392885EC09032301E06D24740C6CD0F4491885EC0E40952CD09D24740C47F645B91885EC014E4E1AD09D24740C5F8D8708E885EC01C812C5F17D24740C5F8D8708E885EC001000000010000000001000000FFFFFFFF0000000003

WKTF:
POLYGON ((-122.13369389713905 47.641338249903328, -122.13370224040689 47.6413757262587, -122.1333490407588 47.64137385244706, -122.13333791672912 47.640834190278355, -122.13326560808042 47.640830442561054, -122.13327395134826 47.640927881965126, -122.13316548821156 47.640926008192594, -122.13316548821156 47.640985970755253, -122.13266210974243 47.640980349278266, -122.13264820396859 47.640740498313249, -122.13273998056964 47.640738624368538, -122.1327427616589 47.64062994152755, -122.13290684658119 47.640633689204094, -122.13290406516451 47.640257045266168, -122.13300696612268 47.640206450914718, -122.13324614045547 47.640182090923588, -122.13324614045547 47.640712390569632, -122.13337407088974 47.640708642898716, -122.13338241415757 47.640643058394232, -122.13346584683593 47.640598086266237, -122.13386354391247 47.64059059079753, -122.13394141473971 47.64065242769297, -122.13396922563248 47.640804208753082, -122.13386632483807 47.640811704191151, -122.13387188734401 47.6409241343097, -122.13369389713905 47.640920386598879, -122.13369389713905 47.641338249903328))

will generate an error

`[System.FormatException] One of the identified items was in an invalid format. `

**Comment by dotMorten** [comment]
@yorek Thanks. Which one generates an error? How are you getting the error?

The best think is if you could clone the repo and add a simple test method to this class that demonstrates the problem:
https://github.com/dotMorten/Microsoft.SqlServer.Types/blob/main/src/Microsoft.SqlServer.Types.Tests/Geography/WktTests.cs

If you run the test you should hopefully see the same error when running against .NET Core (this library), or .NET Framework (which uses the official library)

**Comment by yorek** [comment]
Yep done that, I've opened the issue to that I can correlate the fix I'm about to post :)

**Comment by yorek** [comment]
>If you run the test you should hopefully see the same error when running against .NET Core (this library), or .NET Framework (which uses the official library)

The .NET Framework test, using the official library, doesn't have any problem, and the error was only affecting the .NET Core library (as expected)

**Comment by dotMorten** [comment]
This looks more like a lack of v2 support: https://github.com/dotMorten/Microsoft.SqlServer.Types/issues/9
