### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by olmobrutall** [dotMorten/Microsoft.SqlServer.Types#7]
I'm currently migrating https://github.com/signumsoftware/framework to .Net Core, this project uses `SqlGeometryId` and `SqlHierarchyId` (I made a [pull request](https://github.com/dotMorten/Microsoft.SqlServer.Types/pull/6) to add support), so I would like to take a dependency to this project. 

Is there a nuget package? 

If not, could you create one, or should I?

**Comment by dotMorten** [comment]
There's (now) 5 different SqlServer Types packages on Nuget.org. It's a giant mess. You can just build this solution and you'll have a nuget as output that you can put in your local nuget repo

**Comment by olmobrutall** [comment]
Hi @dotMorten, 

I know was a bit unfriendly, but I'm migrating Signum Framework and many applications depending on it to .Net Core. I didn't want to add this repo as a submodule on each application for something that looks like a temporal problem anyway... will SQL Server team make an official version for .Net Core some day? who knows :(. So making a Nuget looked like the best option to move forward.

 I gave you credit (Authors dotmorten and olmobrutall) and I'm happy to give you ownership of the nuget if you're happy with the name. Otherwise I'll use yours and delete mine when you make one.
