### ISSUE TITLE
MultiPoint issue?

### ISSUE THREAD

**Issue by daylightgis** [dotMorten/Microsoft.SqlServer.Types#72]
The WKT's aren't equal for this example, MultiPoint // double parenthesis replaced with single

Not shown in the Test, we use SQLGeometry.Write function to get the a binary rep to write to SQL Server...  which errors with the below screenshot invalid format.  

Both representations seem valid in SQL Server via SSMS so not ready sure if i'm on to the right problem yet.

` [TestMethod]
        public void TestMultipoint()
        {
            string wkt = "MULTIPOINT((-78.21 43.869))";
            var k = SqlGeometry.Parse(wkt);                    
            var valueWKT = k.STAsText().ToSqlString();
            Assert.AreEqual(wkt, valueWKT);           
        }
`

![geometry_valid_err](https://user-images.githubusercontent.com/7190902/154143872-38c55be4-befa-4fc9-8b3c-54caab1bb3cd.png)

**Comment by Ogre-69** [comment]
To follow up on this one:
If I create a multipoint geometry in sql server, and output to hex, then use the hex to create a geometry I get expected results.
That same geometry, when created in C# using Microsoft.SqlServer.Types generates a binary of:
**0x000000000104010000003D0AD7A3708D53C0AC1C5A643BEF454**0020000000000000000000000000002000000FFFFFFFF0000000004000000000100000001
Which sql server can't parse and throws the above exception.

I suspect that there's something wrong in the hierarchy patterns for multipoint, but I'm struggling to understand the code. You can see that the sql generated binary is identical to the dotmorten one up to the end of the coordinates, and the beginning of what looks like the hierarchy bits.

DECLARE @g geometry;  
SET @g = geometry::STMPointFromText('MULTIPOINT((-78.21 43.869))', 4326);  
SELECT @g;

DECLARE @g geometry;  
SET @g = geometry::STMPointFromText('MULTIPOINT (-78.21 43.869)', 0);  
SELECT @g.STAsBinary();  

DECLARE @g geometry;  
--SET @g = **0x000000000104010000003D0AD7A3708D53C0AC1C5A643BEF4540**01000000010000000002000000FFFFFFFF0000000004000000000000000001
--fromvs = **0x000000000104010000003D0AD7A3708D53C0AC1C5A643BEF4540**020000000000000000000000000002000000FFFFFFFF0000000004000000000100000001
--fromwkb        0x01040000000100000001010000003D0AD7A3708D53C0AC1C5A643BEF4540
SELECT @g.ToString();

**Comment by dotMorten** [comment]
Apparently, the initial OGC specifications were not clear and the community started using the representation that this library is doing for MultiPoint geometries. But apparently OGC has since clarified the specifications and accordingly, the version with extra parenthesis are the correct one. I'll fix that.
