### ISSUE TITLE
Specified type is not registered on the target.

### ISSUE THREAD

**Issue by alexpantyukhin** [dotMorten/Microsoft.SqlServer.Types#73]
I tried to move from the the `Microsoft.SqlServer.Types` to this library. It successfully complied but when I trued to `Insert` with `IDbCommand` the value with `SqlGeography` instance I get:
`System.ArgumentException : Specified type is not registered on the target server.Microsoft.SqlServer.Types.SqlGeography, Microsoft.SqlServer.Types, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null.`

How it could be fixed?

**Comment by thaianhduc** [comment]
@alexpantyukhin how did you fix it? I got the same problem when upgrading from .NETCore 3.1 to .NET8
