### ISSUE TITLE
Upgrade from Framework to Standard

### ISSUE THREAD

**Issue by DanPatten** [dotMorten/Microsoft.SqlServer.Types#83]
Hello, 

I am looking to gradually upgrade several projects one at a time from .NET Framework -> .NET Standard 2.0.

However I have several projects referencing Microsoft.SqlServer.Types.

How do I upgrade the lowest project first to .NET standard 2.0 while still maintaining existing references. I am confused if I should be using this library or something else. 

As a note I am using System.Data.SqlClient everywhere.

Thanks!

**Comment by ErikEJ** [comment]
Just use Microsoft.Data.SqlClient 5 with the latest Microsoft.SqlServer.Types package

**Comment by dotMorten** [comment]
☝️ That. But you'll have to update the SqlClient nuget reference in all your projects that uses sql.
